### ISSUE TITLE
Create Survey Questions

### ISSUE THREAD

**Issue by philmui** [safe-paths-contrib/covid-safe-paths#1]

**Comment by ThomasDuBois** [comment]
This task is in progress among @andrew-sfdc @ppadmanabhan-sf @ShivanKaul and I.

The working notes are here: https://drive.google.com/drive/folders/1zkUf4jmz2p_tzo8QH-o3bYpvqkHJUFfN

Main tasks are:
- Building a "profile" to be stored on the app for some of the CDC's per-person questions (Andrew).
- Building the UX for the survey including transitioning to "upload your waypoints" (Andrew).
- Building the server schema for delivering the survey payload to the app (Shivan)
- Building the server schema for accepting survey responses (later, Prithvi)

Feel free to edit these descriptions and/or add links to working documents.

**Comment by kujenga** [comment]
Update: CDC questions are in a good place

Wondering for the future if there are alternate additional questions that might help us in V2, e.g. asking about loss of smell.

**Comment by kujenga** [comment]
@ThomasDuBois shares that CDC updated the question list they have. Maybe no changes needed for us but there are changes we can follow.

Is this the source of truth? [Self-Assessment Questions (WIP)](https://docs.google.com/document/d/1Q-37obNuIZz2jARz7dsPA6rBKJITolS62IJGp1l08g8/edit)

Yes, that the latest.

@ThomasDuBois will shift out of a previous version of the doc.

**Comment by kujenga** [comment]
Closing this out with the self-reporting PR now filed
