### ISSUE TITLE
Store location data in Realm instead of a key value pair with all location data in a big array

### ISSUE THREAD

**Issue by qingqingliu** [safe-paths-contrib/covid-safe-paths#11]
- [x] Store location data in Realm.io
- [ ] App can retrieve all stored location data from Realm
- [ ] App can purge location data (all or by time range) from Realm

**Comment by troach-sf** [comment]
See relevant issue in public repo here: https://github.com/tripleblindmarket/covid-safe-paths/issues/527

**Comment by kujenga** [comment]
Update from standup: There will be some additional follow-ups and coordination with MIT teams to discuss the current design, there is a backfilling approach for gaps in GPS data that may not be desired in the long term.

Need to determine who the stakeholders are on this, will follow up with Sam.

**Comment by troach-sf** [comment]
Received buy-in from stakeholders.

* Will store precise location in sqlite database and stop reporting location to the existing key/value storage.
* Allowed to clear the existing async-storage key. We will lose backfilled data, and previously run Google Takeout imports. This has been approved as acceptable given circumstances.
* Google takeout imported data will be stored in async-storage under a new key.
* If we need to pull data, only then do we merge different sources (Real/takeout, etc)

**Comment by troach-sf** [comment]
Updated to make note of our usage of Realm, not SQLite

**Comment by kujenga** [comment]
Update: both platforms are storing data in realm, working on wrappers for access from react.

Encryption will be handled in follow-on ticket #29

**Comment by kujenga** [comment]
Update: almost complete with Android wrapper, saving, getting, trimming, etc. Writing wrapper for iOS is next, and then that will be tied into the code.

Expecting today Android side done today.

**Comment by kujenga** [comment]
Update: Android wrapper is fully functional, last piece is migrating existing location data to the new database storage.

Javascript work for this is mostly written as well.

Remaining work is the iOS wrapper and adding encryption in #29

**Comment by kujenga** [comment]
Update: Completed JS portion yesterday, got existing tests passing 100%. Today working on iOS wrapper, hoping to complete that by end of day.

Then next is encryption work.

**Comment by kujenga** [comment]
Update: Finished iOS wrapper, now all wrappers and JS code are complete. PR will be previewed with @aputinski and @qingqingliu to the public repo. Still don't want to merge, since encryption is also a requirement.

But will start getting eyes on it. Tim will be the one merging to upstream, will give him a heads up before submission.

**Comment by kujenga** [comment]
Closing this out! Just encryption and merge remaining
