### ISSUE TITLE
API Integration with Waypoints

### ISSUE THREAD

**Issue by qingqingliu** [safe-paths-contrib/covid-safe-paths#13]
- [ ] Support GET for getting location data
- [ ] Support POST for upload

**Comment by kujenga** [comment]
From Standup, @qingqingliu has some feedback on server design for @ppadmanabhan-sf

**Comment by kujenga** [comment]
Update: Done with integration work, have a few pieces of feedback for @ppadmanabhan-sf on this, need to get those resolved before this is closed out.

It's not currently a heatmap because "weights" are not part of the API/

**Comment by kujenga** [comment]
Update, latest API changes addressed some but not all of the issues with the API. Will also need to address authentication concerns that are more recently discussed.
