### ISSUE TITLE
Implement on-device encryption for Location Tracking data

### ISSUE THREAD

**Issue by kujenga** [safe-paths-contrib/covid-safe-paths#29]
Looking at using https://realm.io/ for this as well

**Comment by ShivanKaul** [comment]
@troach-sf we might still need to have some kind of app authorization, to add some more security on export. Something to keep in mind

**Comment by kujenga** [comment]
No updates here, things progressing. Getting started with Realm, beginning encryption process after that.

Will want review, in particular from a security expert, after implementation.

Issue is still outstanding on Android <23 not entirely secure, just a platform limitation.

**Comment by kujenga** [comment]
Update: Android side completed just minutes ago, iOS done.

Would like a formal security review. iOS was fairly straightforward, Android was more complicated and pulled in a library.

@ShivanKaul will take a look, some discussion of pros/cons of using a library. Will look more closely at the tradeoff here, make sure no older versions of the app are insecure.

Would like Fiaz and his team to review as well. @troach-sf will read out and cc Phil

**Comment by kujenga** [comment]
Update: Comments from @troach-sf that things look generally good. Pending review in the third party library, but otherwise Fiaz confirms that we are good to go.

**Comment by kujenga** [comment]
PR has already been created, pending security approval (which we now have). Tim and Abhishek and others have looked at it, all okay at a high level.

May look at additional tests as well.

Location accuracy is another area where we may be be able to help as a follow-on task. Sam will connect with Tim and Tyler to confirm next steps here as well.

**Comment by kujenga** [comment]
Update: Wrote all tests for the Android side, writing iOS currently. Then can merge, pushing for the end of day today.

Most of the people who need to look at it have done so. Tests will be the last thing before merge.

**Comment by kujenga** [comment]
Update: testing complete on all platforms, PR is ready to go: https://github.com/Path-Check/covid-safe-paths/pull/747

@ShivanKaul shares that code review looks good, Diego on SF security team will be doing some local testing.

**Comment by kujenga** [comment]
Update: Working through last question on whether or not we should backfill data.

Agreed that we should not store data, question is about for detecting intersections. For HAs, don't want to send assumed data points. Intersection is in discussion.

This is holding up merging currently. May just make it configurable so that the decision can be made later on. Discussing with Sam, Abhishek, others on the PR. Sam will make sure that a resolution is reached.

Tyler will check with Diego to get final approval from Salesforce security from local testing.

**Comment by tstirrat** [comment]
788 was merged

**Comment by kujenga** [comment]
Update: @troach-sf will be adding backfill back into the system, they will be annotated as such so that they can be filtered out in the future.

@troach-sf completed it for Android, finishing up iOS now.

Encryption work and location storage improvements are in.

Still pending Diego's completion of review.

**Comment by troach-sf** [comment]
Last bit of work has a PR and is pending review: https://github.com/Path-Check/covid-safe-paths/pull/798

**Comment by kujenga** [comment]
PR is approved, just not yet merged, expect it to come in soon with the #9 security review work complete with no issues.

**Comment by kujenga** [comment]
Closing this out with Tyler's work merged upstream! ref: https://github.com/Path-Check/covid-safe-paths/pulls?q=is%3Apr+author%3Atroach-sf+sort%3Aupdated-desc
