### ISSUE TITLE
Survey Upload API Authentication

### ISSUE THREAD

**Issue by qingqingliu** [safe-paths-contrib/covid-safe-paths#32]
- [x] Support Recaptcha

**Comment by kujenga** [comment]
Update: Work is in progress, here. Still a bit of discussion ongoing.

**Comment by kujenga** [comment]
Update: Implementation is complete for both iOS and Android, just need an account and production-quality web server.

On the backend side, starting with the implementation to support this, captcha validation included. Captcha interface exists, hCaptcha implementation exists. We will keep hCaptcha for now.

**Comment by kujenga** [comment]
Update: Will try out the new URL available through #34
