### ISSUE TITLE
Hosting hCaptcha Page on PrivateKit Server

### ISSUE THREAD

**Issue by qingqingliu** [safe-paths-contrib/covid-safe-paths#34]
- [ ] Host https://safepath-captcha.herokuapp.com/index.html on a PrivateKit Server 
- [ ] Replace the site key in that file with the site key to match the hCaptcah PrivateKit server is using

**Comment by kujenga** [comment]
Update: @imanzano and team talked with @qingqingliu about the requirements, no blockers here, have all the needed information.

Need the real credentials for this to work, site key, etc.

Salesforce should NOT own the production keys here, but can use it for testing. @ppadmanabhan-sf will work with Sam to this end, to get MIT owned hCaptcha credentials: https://www.hcaptcha.com/

**Comment by kujenga** [comment]
Update: Implementation is ready, hosting in Heroku, will be ready for today on our own account. Will need production hCaptcha credentials.

Sam will work on creating hCaptcha today for use here.

**Comment by kujenga** [comment]
Update: There is an endpoint available for this at /v1.0/captcha, @fzavalia or @imanzano to update the spec with the specific information so that @qingqingliu can use it in testing.

**Comment by kujenga** [comment]
This is done! A few tweaks came in for styling today.
