### ISSUE TITLE
Server implementation of survey API and database

### ISSUE THREAD

**Issue by kujenga** [safe-paths-contrib/covid-safe-paths#36]

**Comment by kujenga** [comment]
Update: finished all the endpoints, testing everything now to find any bugs. Deploying on heroku.

@ppadmanabhan-sf reviewed and merged code.

Will share out the endpoints once it is deployed. Will be hardened this week after initial deployment.

**Comment by kujenga** [comment]
Update: code is done, deployed in @imanzano 's heroku account. Next is making sure that integration with mobile app is all aligned.

Endpoints: @aputinski and others have the data here.

@qingqingliu may be able to help with API integration work on mobile app.

**Comment by imanzano** [comment]
The Server is deployed on https://fathomless-mountain-29102.herokuapp.com

**Captcha page**
/v1.0/captcha

**Endpoints**
_Health_
/actuator/health

_Survey_
GET  /v1.0/{app_namespace}/survey
POST /v1.0/{app_namespace}/survey
POST /v1.0/{app_namespace}/survey/{survey_id}/response

All the operations (POST and GET) are protected with Captcha token.

The Server has one app create with namespace "2"

**Comment by kujenga** [comment]
Update:

- Server has been updated so that only POST is protected with captcha
- Next work here is integration testing, any iterations

**Comment by kujenga** [comment]
Closing this out with the Mulesoft folks effort completed.
