### ISSUE TITLE
License scanning for backend server

### ISSUE THREAD

**Issue by kujenga** [safe-paths-contrib/covid-safe-paths#39]
Making sure that we're using properly licensed dependencies, as well as dependencies that have no security issues.

Snyk supports free usage for open source: https://snyk.io/plans/

**Comment by imanzano** [comment]
Our repo is using https://snyk.io/. 
There are no license violations reported by snyk.

**Comment by kujenga** [comment]
It is configured on the separate repo, not on privatekit yet

**Comment by kujenga** [comment]
Request sent to Abhishek to whitelist Snyk on the privatekit org, following instructions here: https://support.snyk.io/hc/en-us/articles/360000921278-How-do-I-authorize-a-new-Github-organization-

**Comment by kujenga** [comment]
Scan has been setup [1] on the https://github.com/PrivateKit/private-kit-service repo, there are three issues raised, I believe these were looked at already but it would be great to document the responses somewhere. The vulnerable modules are:
- `org.dom4j:dom4j`
- `org.hibernate.validator:hibernate-validator`
- `org.yaml:snakeyaml`

@imanzano @ppadmanabhan-sf was the thinking behind these documented anywhere?

[1] https://app.snyk.io/org/privatekit/project/2c0d9ad4-6064-41bf-91b2-30f47dd405ca

**Comment by kujenga** [comment]
Aaron to send invite to @imanzano so that he can double check on this.

**Comment by kujenga** [comment]
@imanzano to post analysis in Slack, sounds like there is no current impact on our service.

**Comment by imanzano** [comment]
I fix the vulnerabilities. I sent the PR to @ppadmanabhan-sf  and it is merged too.

**Comment by kujenga** [comment]
Awesome, Snyk looks clean! Closing this out, thanks so much.
