### ISSUE TITLE
Privacy work items prioritization for V1

### ISSUE THREAD

**Issue by ShivanKaul** [safe-paths-contrib/covid-safe-paths#42]
Agree on prioritization for https://salesforce.quip.com/GyxUADNboSYg

**Comment by kujenga** [comment]
Update: Meeting with Paolo today, will be discussing this further. Sam is in discussion with MIT legal review. Working through "P0" items for an upcoming release.

Also connecting with a red team out of princeton who will focus on this area.

**Comment by kujenga** [comment]
This is complete, because of the reduced scope, all issues are okay.
