### ISSUE TITLE
Augment server to support language-specific survey responses

### ISSUE THREAD

**Issue by kujenga** [safe-paths-contrib/covid-safe-paths#52]
@imanzano will take this on, working with @ppadmanabhan-sf . This is in support of Localization, ref https://github.com/safe-paths-contrib/covid-safe-paths/issues/51

**Comment by kujenga** [comment]
Update: @imanzano working with a few comments from @ppadmanabhan-sf to support this functionality.

**Comment by imanzano** [comment]
Update: The work is finished, available in our Heroku environment and Merge in Prithvi repository.

The details of the implementation are:

> Language Support
Survey API supports store surveys in different languages. The API uses the standard HTTP Header accept-language in order to determine the language to associate with the survey.
> For Example, POST a new survey
> 
> curl --location --request POST 'https://localhost:8080/v1.0/myNamespace/survey/' --header 'Content-Type: application/json' --header 'Accept-Language: en' --data-raw '{ ... }'
> 
> The HTTP Header accept-language is MANDATORY. If the header is not present a HTTP Bad Request (400) will be returned.

> 
> List of Surveys => GET /v1.0/{app_namespace}/survey
> Http-Header: accept-language [REQUIRED]
> If present it will return all the surveys for the app_namespace that match the accept-language)
> 
> Post a new Survey=> POST /v1.0/{app_namespace}/survey
> Http-Header: accept-language [REQUIRED]
> The new survey will be stored setting the accept-language as survey_language field
> 
> Get a specific Survey => GET /v1.0/{app_namespace}/survey/{survey_id}
> There is no need to specify the lang because the survey_id is unique it is attached to a language
>

**Comment by kujenga** [comment]
server has been updated and the code is in the open source repo. Closing this out!
