### ISSUE TITLE
Improve accuracy of location tracking

### ISSUE THREAD

**Issue by kujenga** [safe-paths-contrib/covid-safe-paths#56]
@troach-sf brings up issues with accuracy of cell-tower triangulation, current app shows movement even when stationary at home.

Okay for memory aid, not so for contact tracing.

Focus for V1 is on memory aid.

**Comment by kujenga** [comment]
Update: @troach-sf rolling off on Monday, probably won't be able to dig into this. Will provide a commit that's a starting point for improvements at least on the Android side.

Will need someone else to take on the bulk of the work. ack from SAm

**Comment by troach-sf** [comment]
Quick spike of what a fix could look like: https://github.com/troach-sf/background-geolocation-android/tree/spike/minimum-accuracy-threshold

**Comment by kujenga** [comment]
Update: @troach-sf to follow up with some comments in SafePaths GitHub to share any context/ideas here to close out this thread from his point of view.

**Comment by kujenga** [comment]
Closing this out, seems to be a clearly known issue for the project, so they can track that in existing issues.
